name: CI
on:
  push:
    branches:
      - HusnainQadri

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipreqs pylint black
        pipreqs ./ --force
        pip install -r requirements.txt

    - name: Run Pylint
      run: |
        pylint test.py

    - name: Run Black
      run: |
        black test.py

    - name: Run tests
      run: |
        python test.py

    - name: Merge to master branch
      if: ${{ success() }}
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        branch: master
        commit-message: "Merge HusnainQadri branch"
        title: "Merge HusnainQadri branch"
        body: "This is an automated pull request created by GitHub Actions."